version: '3.0'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile

    ports: 
     - 3000:3000

    volumes:
      - ./:/app/

    networks:
      - mynetwork

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=eecomerce

    ports:
      - 5432:5432
    
    volumes:
      - database:/var/lib/postgresql

    networks:
      - mynetwork

volumes:
  database:
    driver: local

networks:
  mynetwork: 
    driver: bridge